import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { lookup as defaultDnsLookup } from "node:dns/promises";
import { execFile as defaultExecFile } from "node:child_process";
import { promisify } from "node:util";
import path from "node:path";
import { inflateRawSync } from "node:zlib";

import {
  R31_ARCHIVE_FIELDS,
  R31_ENDPOINTS,
  R31_FIELD_MAPPINGS,
  R31_SYMBOLS,
  R31_TIMESTAMP_MAPPINGS,
  evaluateR31Mapping,
  filterR31LiveRows,
  summarizeR31Field,
  type R31ArchiveField,
  type R31ArchiveRow,
  type R31Endpoint,
  type R31LiveRow,
  type R31Symbol,
  type R31TimestampMapping,
} from "./round-031-binance-metrics-overlap.ts";

export const R32_RESEARCH_ROUND_ID = "baseline-002-research-round-032" as const;
export const R32_CLASSIFICATION = "EXECUTION_ENVIRONMENT_AND_PARSER_REPROBE_ONLY" as const;
export const R32_BASE_BRANCH = "research/round-015-beta-alpha-decomposition" as const;
export const R32_BASE_SHA = "96f14392b02ea492a1b2c6f20b47334a3bf3234a" as const;
export const R32_BRANCH = "research/round-032-binance-metrics-execution-environment-reprobe" as const;
export const R32_DATE = "2026-09-18" as const;
export const R32_START_TIME = 1_789_689_600_000 as const;
export const R32_END_TIME = 1_789_775_999_999 as const;
export const R32_ARCHIVE_BASE_URL = "https://data.binance.vision/data/futures/um/daily/metrics" as const;
export const R32_LIVE_BASE_URL = "https://fapi.binance.com/futures/data" as const;
export const R32_PROBE_URL = "https://fapi.binance.com/fapi/v1/time" as const;
export const R32_PERIOD = "5m" as const;
export const R32_LIMIT = 500 as const;
export const R32_NUMERIC_TOLERANCE = "0.5 * 10^(-liveDecimalPlaces) + 1e-12" as const;
export const R32_MIN_NUMERIC_AGREEMENT = 0.995 as const;
export const R32_MIN_TIMESTAMP_COVERAGE = 0.99 as const;
export const R32_SYMBOLS = R31_SYMBOLS;
export const R32_ENDPOINTS = R31_ENDPOINTS;
export const R32_FIELD_MAPPINGS = R31_FIELD_MAPPINGS;
export const R32_TIMESTAMP_MAPPINGS = R31_TIMESTAMP_MAPPINGS;

export const R32_GOVERNANCE = Object.freeze({
  economicOutcomeFilesRead: false,
  economicEvaluationPerformed: false,
  tradingEconomicMetricsCalculated: false,
  modelFitCount: 0,
  candidateCount: 0,
  championCount: 0,
  selectedAlertCount: 0,
  forwardEconomicValuesRead: false,
  forwardReturnRead: false,
  performanceExecutionCount: 0,
  candidateExecutableFrozen: false,
  forwardCandidateExists: false,
  forwardValidationAuthorized: false,
  automaticTrading: false,
  humanDecisionRequired: true,
  productionUnchanged: true,
  emailRestorationAuthorized: false,
  baseline002Status: "NOT_FROZEN",
  m3GStatus: "EXCLUDED_FROM_ROUND_032",
  m3JStatus: "BLOCKED",
  m4Status: "NOT_STARTED",
} as const);

export type R32ParserMode = "EPOCH_MS" | "EPOCH_SECONDS" | "UTC_DATETIME_STRING" | "ISO_WITH_ZONE";
export type R32Transport = "NODE_FETCH" | "CURL";
export type R32ErrorClass = "NETWORK" | "HTTP" | "NON_JSON" | "NON_ARRAY" | "SCHEMA" | "ARCHIVE" | "CHECKSUM" | "DUPLICATE" | "MAPPING" | "NUMERIC" | "RECEIPT";
export type R32ParserResult = Readonly<{ timestamp: number; mode: R32ParserMode }>;

export function parseR32ArchiveCreateTime(raw: unknown): R32ParserResult {
  const text = typeof raw === "number" && Number.isFinite(raw) ? String(raw) : typeof raw === "string" ? raw.trim() : "";
  if (text.length === 0) throw new Error("Archive create_time is empty.");
  if (/^[+-]?\d+$/u.test(text)) {
    const value = Number(text);
    if (!Number.isSafeInteger(value)) throw new Error("Archive create_time integer is unsafe.");
    if (value >= 1_000_000_000_000 && value < 10_000_000_000_000) return Object.freeze({ timestamp: value, mode: "EPOCH_MS" });
    if (value >= 1_000_000_000 && value < 10_000_000_000) return Object.freeze({ timestamp: value * 1000, mode: "EPOCH_SECONDS" });
    throw new Error("Archive create_time integer is outside the frozen epoch ranges.");
  }
  const utc = /^(\d{4})-(\d{2})-(\d{2}) (\d{2}):(\d{2}):(\d{2})(?:\.(\d{3}))?$/u.exec(text);
  if (utc) {
    const milliseconds = Number(utc[7] ?? 0);
    const timestamp = Date.UTC(Number(utc[1]), Number(utc[2]) - 1, Number(utc[3]), Number(utc[4]), Number(utc[5]), Number(utc[6]), milliseconds);
    const check = new Date(timestamp);
    if (check.getUTCFullYear() !== Number(utc[1]) || check.getUTCMonth() !== Number(utc[2]) - 1 || check.getUTCDate() !== Number(utc[3]) || check.getUTCHours() !== Number(utc[4]) || check.getUTCMinutes() !== Number(utc[5]) || check.getUTCSeconds() !== Number(utc[6]) || check.getUTCMilliseconds() !== milliseconds) throw new Error("Archive create_time UTC datetime is invalid.");
    return Object.freeze({ timestamp, mode: "UTC_DATETIME_STRING" });
  }
  if (/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?(?:Z|\+00:00)$/u.test(text)) {
    const timestamp = Date.parse(text);
    if (!Number.isFinite(timestamp)) throw new Error("Archive create_time ISO value is invalid.");
    return Object.freeze({ timestamp, mode: "ISO_WITH_ZONE" });
  }
  throw new Error("Archive create_time format is not one of the frozen UTC formats.");
}

export const R32_PROTOCOL_OBJECT = Object.freeze({
  schemaVersion: "m3-r32-binance-metrics-execution-environment-protocol-001",
  researchRoundId: R32_RESEARCH_ROUND_ID,
  classification: R32_CLASSIFICATION,
  base: Object.freeze({ branch: R32_BASE_BRANCH, sha: R32_BASE_SHA }),
  branch: R32_BRANCH,
  fixedWindow: Object.freeze({ date: R32_DATE, startTime: R32_START_TIME, endTime: R32_END_TIME, timezone: "UTC" }),
  symbols: R31_SYMBOLS,
  endpoints: R31_ENDPOINTS,
  mappings: R31_FIELD_MAPPINGS,
  timestampMappings: Object.freeze({ options: R31_TIMESTAMP_MAPPINGS, minimumCoverage: R32_MIN_TIMESTAMP_COVERAGE }),
  numericAgreement: Object.freeze({ tolerance: R32_NUMERIC_TOLERANCE, minimumRate: R32_MIN_NUMERIC_AGREEMENT }),
  archive: Object.freeze({ baseUrl: R32_ARCHIVE_BASE_URL, zipFiles: 5, checksumFiles: 5, exactFields: R31_ARCHIVE_FIELDS, parserModes: ["EPOCH_MS", "EPOCH_SECONDS", "UTC_DATETIME_STRING", "ISO_WITH_ZONE"] }),
  transport: Object.freeze({ probeUrl: R32_PROBE_URL, nodeTimeoutSeconds: 10, curlConnectTimeoutSeconds: 10, curlMaxTimeSeconds: 15, curlRetry: 0, formalLogicalRequests: 25, oneAttemptPerLogicalRequest: true }),
  receipt: Object.freeze({ executionType: "BINANCE_METRICS_EXECUTION_ENVIRONMENT_REPROBE", exactlyOneInvocation: true }),
  currentOnly: Object.freeze({ historicalRegimeMappingEstablished: false, fullHistoricalCoverageCertified: false }),
  economics: Object.freeze({ economicOutcomeFilesRead: false, economicEvaluationPerformed: false, tradingEconomicMetricsCalculated: false, modelFitCount: 0, candidateCount: 0, championCount: 0, selectedAlertCount: 0 }),
  governance: R32_GOVERNANCE,
} as const);

export type R32ArchiveRow = R31ArchiveRow;
export type R32RequestEvidence = Readonly<{
  symbol: string; endpointOrArchivePath: string; selectedTransport: R32Transport; requestUrl: string; startedAt: string; completedAt: string; localReceiptTimestamp: string; httpStatus: number | null; ok: boolean; contentType: string | null; responseBytes: number | null; rawPayloadSha256: string | null; rawLiveRowCount: number | null; outOfWindowRowCount: number | null; filteredRowCount: number | null; exactDuplicateCount: number | null; conflictingDuplicateCount: number | null; errorClass: R32ErrorClass | null; errorCode: string | null; errorMessage: string | null; nestedCauseCode: string | null; stderrPreview: string;
}>;
export type R32ArchiveEvidence = Readonly<{
  symbol: R31Symbol; url: string; checksumUrl: string; transportAvailable: boolean; zipHttpStatus: number | null; checksumHttpStatus: number | null; publishedChecksum: string | null; localSha256: string | null; checksumValid: boolean; headerSchemaValid: boolean; schemaValid: boolean; timestampParserValid: boolean; createTimeFormatCounts: Readonly<Record<R32ParserMode, number>>; duplicateValid: boolean; rowCount: number; firstTimestamp: number | null; lastTimestamp: number | null; exactDuplicateCount: number; conflictingDuplicateCount: number; zipRequest: R32RequestEvidence; checksumRequest: R32RequestEvidence; errorClass: R32ErrorClass | null; errorMessage: string | null;
}>;
export type R32TransportPreflight = Readonly<{
  dnsLookup: Readonly<{ addresses: readonly string[]; errorCode: string | null }>;
  nodeFetch: Readonly<{ attempted: true; success: boolean; startedAt: string; completedAt: string; httpStatus: number | null; contentType: string | null; responseBytes: number | null; payloadSha256: string | null; errorName: string | null; errorMessage: string | null; nestedCauseCode: string | null; nestedCauseMessage: string | null }>;
  curl: Readonly<{ attempted: boolean; commandAvailable: boolean; success: boolean; exitCode: number | null; httpStatus: number | null; stdoutBytes: number | null; stdoutSha256: string | null; stderrPreview: string; errorName: string | null; errorMessage: string | null }>;
  proxyEnvironment: Readonly<{ HTTP_PROXY: boolean; HTTPS_PROXY: boolean; ALL_PROXY: boolean; NO_PROXY: boolean; proxySchemes: Readonly<Record<string, string | null>> }>;
  selectedTransport: R32Transport | null;
}>;
export type R32FieldSummary = Readonly<{ fieldId: string; archiveField: R31ArchiveField; liveEndpoint: R31Endpoint; liveField: string; admitted: boolean; dominantMapping: R31TimestampMapping | null; minimumTimestampCoverage: number; minimumNumericAgreement: number }>;
export type R32Result = Readonly<{
  schemaVersion: "m3-r32-binance-metrics-execution-environment-result-001"; researchRoundId: typeof R32_RESEARCH_ROUND_ID; classification: typeof R32_CLASSIFICATION; protocolCommitSha: string; runId: string; r32ExecutionCount: 1; fixedWindow: Readonly<{ date: typeof R32_DATE; startTime: typeof R32_START_TIME; endTime: typeof R32_END_TIME; timezone: "UTC" }>; inheritedR31Conclusion: Readonly<{ sourceClassification: "SOURCE_REPROBE_INCONCLUSIVE_DUE_TO_LIVE_REACHABILITY"; r31ReprobeExecutionCount: 1 }>; archiveEvidence: readonly R32ArchiveEvidence[]; archiveFilesAvailable: number; checksumValidFiles: number; schemaValidFiles: number; timestampParserValidFiles: number; archiveOverlapReady: boolean; executionEnvironment: R32TransportPreflight; formalMappingExecutionCount: 0 | 1; liveLogicalRequests: 25; liveSuccessfulRequests: number; liveFailedRequests: number; requestEvidence: readonly R32RequestEvidence[]; fieldSummaries: readonly R32FieldSummary[]; admittedFields: readonly string[]; rejectedFields: readonly string[]; admittedFieldCount: number; currentRegimeMappingEstablished: boolean; historicalRegimeMappingEstablished: false; fullHistoricalCoverageCertified: false; sourceClassification: string; sourceNextStage: string; economicOutcomeFilesRead: false; economicEvaluationPerformed: false; tradingEconomicMetricsCalculated: false; modelFitCount: 0; candidateCount: 0; championCount: 0; selectedAlertCount: 0; governance: typeof R32_GOVERNANCE;
}>;
export type R32Fetch = (input: string, init?: RequestInit) => Promise<Response>;
export type R32DnsLookup = (hostname: string) => Promise<readonly string[]>;
export type R32CurlResult = Readonly<{ commandAvailable: boolean; exitCode: number | null; httpStatus: number | null; stdout: Uint8Array; stderr: string; errorName?: string | null; errorMessage?: string | null }>;
export type R32CurlRunner = (url: string, args: readonly string[]) => Promise<R32CurlResult>;
export type R32Clock = () => Date;

function sha256(value: Uint8Array | string): string { return createHash("sha256").update(value).digest("hex"); }
export function r32ResultSha256(result: R32Result): string { return sha256(stableJson(result)); }
function stableJson(value: unknown): string { if (value === null || typeof value !== "object") return JSON.stringify(value) ?? "null"; if (Array.isArray(value)) return `[${value.map(stableJson).join(",")}]`; const record = value as Record<string, unknown>; return `{${Object.keys(record).sort().map((key) => `${JSON.stringify(key)}:${stableJson(record[key])}`).join(",")}}`; }
function iso(clock: R32Clock): string { return clock().toISOString(); }
function randomRunId(): string { return `r32-${sha256(`${process.pid}:${Math.random()}:${new Date().toISOString()}`).slice(0, 24)}`; }
function errorInfo(error: unknown): Readonly<{ name: string; message: string; code: string | null; nestedCauseCode: string | null; nestedCauseMessage: string | null }> {
  const first = error as { name?: unknown; message?: unknown; code?: unknown; cause?: unknown }; let cause: unknown = first?.cause; let nestedCauseCode: string | null = null; let nestedCauseMessage: string | null = null;
  for (let depth = 0; depth < 8 && cause; depth += 1) { const record = cause as { code?: unknown; message?: unknown; cause?: unknown }; if (nestedCauseCode === null && typeof record.code === "string") nestedCauseCode = record.code; if (nestedCauseMessage === null && typeof record.message === "string") nestedCauseMessage = record.message; cause = record.cause; }
  return Object.freeze({ name: typeof first?.name === "string" ? first.name : "Error", message: typeof first?.message === "string" ? first.message : String(error), code: typeof first?.code === "string" ? first.code : null, nestedCauseCode, nestedCauseMessage });
}
function bodyPreview(bytes: Uint8Array): string { return Buffer.from(bytes).toString("utf8").slice(0, 1000); }
function emptyEvidence(symbol: string, name: string, transport: R32Transport, url: string, startedAt: string, completedAt: string, info: ReturnType<typeof errorInfo>, errorClass: R32ErrorClass = "NETWORK", stderrPreview = ""): R32RequestEvidence { return Object.freeze({ symbol, endpointOrArchivePath: name, selectedTransport: transport, requestUrl: url, startedAt, completedAt, localReceiptTimestamp: completedAt, httpStatus: null, ok: false, contentType: null, responseBytes: null, rawPayloadSha256: null, rawLiveRowCount: null, outOfWindowRowCount: null, filteredRowCount: null, exactDuplicateCount: null, conflictingDuplicateCount: null, errorClass, errorCode: info.code, errorMessage: info.message, nestedCauseCode: info.nestedCauseCode, stderrPreview }); }
async function withTimeout<T>(promise: Promise<T>, milliseconds: number): Promise<T> { let timer: ReturnType<typeof setTimeout> | undefined; try { return await Promise.race([promise, new Promise<T>((_, reject) => { timer = setTimeout(() => reject(new Error(`TIMEOUT_${milliseconds}MS`)), milliseconds); })]); } finally { if (timer) clearTimeout(timer); } }
async function requestNode(symbol: string, name: string, url: string, fetchImpl: R32Fetch, clock: R32Clock, timeoutMs = 10_000): Promise<{ evidence: R32RequestEvidence; body: Uint8Array | null }> {
  const startedAt = iso(clock);
  try { const response = await withTimeout(fetchImpl(url, { method: "GET", headers: { accept: "application/json, text/plain, */*" } }), timeoutMs); const body = new Uint8Array(await response.arrayBuffer()); const completedAt = iso(clock); const ok = response.ok && response.status >= 200 && response.status < 300; const evidence = Object.freeze({ symbol, endpointOrArchivePath: name, selectedTransport: "NODE_FETCH" as const, requestUrl: url, startedAt, completedAt, localReceiptTimestamp: completedAt, httpStatus: response.status, ok, contentType: response.headers.get("content-type"), responseBytes: body.byteLength, rawPayloadSha256: sha256(body), rawLiveRowCount: null, outOfWindowRowCount: null, filteredRowCount: null, exactDuplicateCount: null, conflictingDuplicateCount: null, errorClass: ok ? null : "HTTP" as const, errorCode: null, errorMessage: ok ? null : `HTTP ${response.status}`, nestedCauseCode: null, stderrPreview: "" }); return { evidence, body }; }
  catch (error) { const completedAt = iso(clock); return { evidence: emptyEvidence(symbol, name, "NODE_FETCH", url, startedAt, completedAt, errorInfo(error)), body: null }; }
}
function archiveUrls(symbol: R31Symbol): { url: string; checksumUrl: string; path: string } { const archivePath = `${symbol}/${symbol}-metrics-${R32_DATE}.zip`; const url = `${R32_ARCHIVE_BASE_URL}/${archivePath}`; return { url, checksumUrl: `${url}.CHECKSUM`, path: archivePath }; }
function liveUrl(symbol: R31Symbol, endpoint: R31Endpoint): string { const url = new URL(`${R32_LIVE_BASE_URL}/${endpoint}`); url.search = new URLSearchParams({ symbol, period: R32_PERIOD, startTime: String(R32_START_TIME), endTime: String(R32_END_TIME), limit: String(R32_LIMIT) }).toString(); return url.toString(); }
function checksumFromBody(body: Uint8Array | null): string | null { return body ? Buffer.from(body).toString("utf8").match(/\b[a-f0-9]{64}\b/iu)?.[0]?.toLowerCase() ?? null : null; }
async function defaultCurlRunner(url: string, args: readonly string[]): Promise<R32CurlResult> {
  const execFile = promisify(defaultExecFile); const executable = process.platform === "win32" ? "curl.exe" : "curl";
  try { const result = await execFile(executable, [...args, url], { encoding: "buffer", maxBuffer: 50 * 1024 * 1024 }); const raw = new Uint8Array(result.stdout as Buffer); const marker = /\n(\d{3})\s*$/u.exec(Buffer.from(raw).toString("latin1")); const stdout = marker ? raw.slice(0, marker.index) : raw; return Object.freeze({ commandAvailable: true, exitCode: 0, httpStatus: marker ? Number(marker[1]) : null, stdout, stderr: String(result.stderr ?? "").slice(0, 1000) }); }
  catch (error) { const info = errorInfo(error); const record = error as { stdout?: unknown; stderr?: unknown; status?: unknown }; return Object.freeze({ commandAvailable: info.code !== "ENOENT", exitCode: typeof record.status === "number" ? record.status : null, httpStatus: null, stdout: record.stdout instanceof Buffer ? new Uint8Array(record.stdout) : new Uint8Array(), stderr: typeof record.stderr === "string" ? record.stderr.slice(0, 1000) : "", errorName: info.name, errorMessage: info.message }); }
}
async function requestCurl(symbol: string, name: string, url: string, curlRunner: R32CurlRunner, clock: R32Clock): Promise<{ evidence: R32RequestEvidence; body: Uint8Array | null }> {
  const startedAt = iso(clock); const args = ["--silent", "--show-error", "--fail-with-body", "--connect-timeout", "10", "--max-time", "15", "--retry", "0", "--write-out", "\\n%{http_code}"];
  try { const result = await curlRunner(url, args); const completedAt = iso(clock); const ok = result.exitCode === 0 && result.httpStatus !== null && result.httpStatus >= 200 && result.httpStatus < 300; const body = result.stdout; const evidence = Object.freeze({ symbol, endpointOrArchivePath: name, selectedTransport: "CURL" as const, requestUrl: url, startedAt, completedAt, localReceiptTimestamp: completedAt, httpStatus: result.httpStatus, ok, contentType: null, responseBytes: body.byteLength, rawPayloadSha256: sha256(body), rawLiveRowCount: null, outOfWindowRowCount: null, filteredRowCount: null, exactDuplicateCount: null, conflictingDuplicateCount: null, errorClass: ok ? null : result.exitCode === 0 ? "HTTP" as const : "NETWORK" as const, errorCode: result.exitCode === 0 ? null : `CURL_EXIT_${result.exitCode ?? "UNKNOWN"}`, errorMessage: ok ? null : (result.errorMessage ?? (result.stderr.slice(0, 1000) || `curl exit ${result.exitCode ?? "unknown"}`)), nestedCauseCode: null, stderrPreview: result.stderr.slice(0, 1000) }); return { evidence, body: ok ? body : body.byteLength > 0 ? body : null }; }
  catch (error) { const completedAt = iso(clock); return { evidence: emptyEvidence(symbol, name, "CURL", url, startedAt, completedAt, errorInfo(error)), body: null }; }
}
async function requestTransport(symbol: string, name: string, url: string, transport: R32Transport, fetchImpl: R32Fetch, curlRunner: R32CurlRunner, clock: R32Clock): Promise<{ evidence: R32RequestEvidence; body: Uint8Array | null }> { return transport === "NODE_FETCH" ? requestNode(symbol, name, url, fetchImpl, clock) : requestCurl(symbol, name, url, curlRunner, clock); }

function little16(bytes: Uint8Array, offset: number): number { return bytes[offset]! | (bytes[offset + 1]! << 8); }
function little32(bytes: Uint8Array, offset: number): number { return (bytes[offset]! | (bytes[offset + 1]! << 8) | (bytes[offset + 2]! << 16) | (bytes[offset + 3]! << 24)) >>> 0; }
function zipEntries(bytes: Uint8Array): readonly Uint8Array[] {
  let eocd = -1; for (let i = bytes.length - 22; i >= Math.max(0, bytes.length - 65_557); i -= 1) if (little32(bytes, i) === 0x06054b50) { eocd = i; break; }
  if (eocd < 0) throw new Error("ZIP end-of-central-directory record is missing."); const total = little16(bytes, eocd + 10); const centralOffset = little32(bytes, eocd + 16); const entries: Uint8Array[] = []; let cursor = centralOffset;
  for (let i = 0; i < total; i += 1) { if (little32(bytes, cursor) !== 0x02014b50) throw new Error("ZIP central directory entry is invalid."); const method = little16(bytes, cursor + 10); const compressedSize = little32(bytes, cursor + 20); const localOffset = little32(bytes, cursor + 42); const nameLength = little16(bytes, cursor + 28); const extraLength = little16(bytes, cursor + 30); const commentLength = little16(bytes, cursor + 32); cursor += 46 + nameLength + extraLength + commentLength; if (little32(bytes, localOffset) !== 0x04034b50) throw new Error("ZIP local entry is invalid."); const localNameLength = little16(bytes, localOffset + 26); const localExtraLength = little16(bytes, localOffset + 28); const start = localOffset + 30 + localNameLength + localExtraLength; const compressed = bytes.slice(start, start + compressedSize); if (method === 0) entries.push(compressed); else if (method === 8) entries.push(new Uint8Array(inflateRawSync(compressed))); else throw new Error(`Unsupported ZIP compression method ${method}.`); }
  return Object.freeze(entries);
}
function csvRows(text: string): readonly string[][] { const rows: string[][] = []; let row: string[] = []; let cell = ""; let quoted = false; for (let i = 0; i < text.length; i += 1) { const c = text[i]!; if (quoted) { if (c === '"' && text[i + 1] === '"') { cell += '"'; i += 1; } else if (c === '"') quoted = false; else cell += c; } else if (c === '"') quoted = true; else if (c === ",") { row.push(cell); cell = ""; } else if (c === "\n") { row.push(cell.replace(/\r$/u, "")); rows.push(row); row = []; cell = ""; } else cell += c; } if (cell.length > 0 || row.length > 0) { row.push(cell); rows.push(row); } return Object.freeze(rows); }
function archiveRecords(bytes: Uint8Array): { records: readonly Record<string, string>[]; headerSchemaValid: boolean } { const entry = zipEntries(bytes).find((candidate) => Buffer.from(candidate).toString("utf8").trim().length > 0); if (!entry) throw new Error("ZIP contains no non-empty data entry."); const text = Buffer.from(entry).toString("utf8").replace(/^\uFEFF/u, ""); const trimmed = text.trim(); if (trimmed.startsWith("[")) { const parsed: unknown = JSON.parse(trimmed); if (!Array.isArray(parsed) || !parsed.every((item) => item !== null && typeof item === "object" && !Array.isArray(item))) throw new Error("Archive JSON payload is not an array of objects."); const records = parsed as Record<string, string>[]; const headerSchemaValid = records.every((record) => Object.keys(record).length === R31_ARCHIVE_FIELDS.length && R31_ARCHIVE_FIELDS.every((field) => typeof record[field] === "string")); return { records: Object.freeze(records), headerSchemaValid }; } const rows = csvRows(text); const header = rows[0] ?? []; const headerSchemaValid = header.length === R31_ARCHIVE_FIELDS.length && header.every((value, index) => value === R31_ARCHIVE_FIELDS[index]); if (!headerSchemaValid) return { records: Object.freeze([]), headerSchemaValid: false }; return { records: Object.freeze(rows.slice(1).filter((row) => row.length > 1).map((row) => Object.fromEntries(header.map((field, index) => [field, row[index] ?? ""])))), headerSchemaValid: true }; }

export function parseR32ArchiveRows(bytes: Uint8Array, symbol: R31Symbol): Readonly<{ rows: readonly R32ArchiveRow[]; headerSchemaValid: boolean; timestampParserValid: boolean; createTimeFormatCounts: Readonly<Record<R32ParserMode, number>>; exactDuplicateCount: number; conflictingDuplicateCount: number; duplicateValid: boolean }> {
  const parsed = archiveRecords(bytes); const counts: Record<R32ParserMode, number> = { EPOCH_MS: 0, EPOCH_SECONDS: 0, UTC_DATETIME_STRING: 0, ISO_WITH_ZONE: 0 }; const grouped = new Map<number, R32ArchiveRow[]>(); if (!parsed.headerSchemaValid) return Object.freeze({ rows: [], headerSchemaValid: false, timestampParserValid: false, createTimeFormatCounts: Object.freeze(counts), exactDuplicateCount: 0, conflictingDuplicateCount: 0, duplicateValid: false });
  let timestampParserValid = true;
  for (const record of parsed.records) { const missing = R31_ARCHIVE_FIELDS.find((field) => typeof record[field] !== "string"); if (missing || record.symbol !== symbol) { timestampParserValid = false; continue; } try { const parsedTime = parseR32ArchiveCreateTime(record.create_time); counts[parsedTime.mode] += 1; const row = Object.freeze({ timestamp: parsedTime.timestamp, symbol, fields: Object.freeze({ ...record }) as Readonly<Record<R31ArchiveField, string>> }); const group = grouped.get(parsedTime.timestamp) ?? []; group.push(row); grouped.set(parsedTime.timestamp, group); } catch { timestampParserValid = false; } }
  if (!timestampParserValid) return Object.freeze({ rows: [], headerSchemaValid: true, timestampParserValid: false, createTimeFormatCounts: Object.freeze(counts), exactDuplicateCount: 0, conflictingDuplicateCount: 0, duplicateValid: false });
  let exactDuplicateCount = 0; let conflictingDuplicateCount = 0; const rows: R32ArchiveRow[] = []; for (const group of grouped.values()) { const identity = stableJson(group[0]!.fields); if (group.some((row) => stableJson(row.fields) !== identity)) conflictingDuplicateCount += group.length - 1; else exactDuplicateCount += Math.max(0, group.length - 1); rows.push(group[0]!); } rows.sort((left, right) => left.timestamp - right.timestamp);
  return Object.freeze({ rows: Object.freeze(rows), headerSchemaValid: true, timestampParserValid: rows.length > 0, createTimeFormatCounts: Object.freeze(counts), exactDuplicateCount, conflictingDuplicateCount, duplicateValid: conflictingDuplicateCount === 0 });
}
function proxyEvidence(env: Partial<NodeJS.ProcessEnv>): R32TransportPreflight["proxyEnvironment"] { const names = ["HTTP_PROXY", "HTTPS_PROXY", "ALL_PROXY", "NO_PROXY"] as const; const schemes = Object.fromEntries(names.map((name) => { const raw = env[name]; if (!raw) return [name, null]; try { return [name, new URL(raw).protocol.replace(/:$/u, "")]; } catch { return [name, "redacted-invalid"] as const; } })) as Record<string, string | null>; return Object.freeze({ HTTP_PROXY: Boolean(env.HTTP_PROXY), HTTPS_PROXY: Boolean(env.HTTPS_PROXY), ALL_PROXY: Boolean(env.ALL_PROXY), NO_PROXY: Boolean(env.NO_PROXY), proxySchemes: Object.freeze(schemes) }); }
async function runPreflight(fetchImpl: R32Fetch, curlRunner: R32CurlRunner, dnsLookup: R32DnsLookup, clock: R32Clock, env: Partial<NodeJS.ProcessEnv>): Promise<R32TransportPreflight> { let addresses: readonly string[] = []; let dnsError: string | null = null; try { addresses = await dnsLookup("fapi.binance.com"); } catch (error) { const info = errorInfo(error); dnsError = info.code ?? info.message; } const node = await requestNode("__probe__", "transport-preflight", R32_PROBE_URL, fetchImpl, clock, 10_000); const nodeInfo = node.evidence; const nodeDiag = Object.freeze({ attempted: true as const, success: nodeInfo.ok, startedAt: nodeInfo.startedAt, completedAt: nodeInfo.completedAt, httpStatus: nodeInfo.httpStatus, contentType: nodeInfo.contentType, responseBytes: nodeInfo.responseBytes, payloadSha256: nodeInfo.rawPayloadSha256, errorName: nodeInfo.errorClass ? "FetchError" : null, errorMessage: nodeInfo.errorMessage, nestedCauseCode: nodeInfo.nestedCauseCode, nestedCauseMessage: null }); let curl: R32TransportPreflight["curl"] = Object.freeze({ attempted: false, commandAvailable: false, success: false, exitCode: null, httpStatus: null, stdoutBytes: null, stdoutSha256: null, stderrPreview: "", errorName: null, errorMessage: null }); if (!nodeInfo.ok) { const result = await curlRunner(R32_PROBE_URL, ["--silent", "--show-error", "--fail-with-body", "--connect-timeout", "10", "--max-time", "15", "--retry", "0", "--write-out", "\\n%{http_code}"]); curl = Object.freeze({ attempted: true, commandAvailable: result.commandAvailable, success: result.exitCode === 0 && result.httpStatus !== null && result.httpStatus >= 200 && result.httpStatus < 300, exitCode: result.exitCode, httpStatus: result.httpStatus, stdoutBytes: result.stdout.byteLength, stdoutSha256: result.stdout.byteLength > 0 ? sha256(result.stdout) : null, stderrPreview: result.stderr.slice(0, 1000), errorName: result.errorName ?? null, errorMessage: result.errorMessage ?? null }); } return Object.freeze({ dnsLookup: Object.freeze({ addresses: Object.freeze([...addresses]), errorCode: dnsError }), nodeFetch: nodeDiag, curl, proxyEnvironment: proxyEvidence(env), selectedTransport: nodeInfo.ok ? "NODE_FETCH" : curl.success ? "CURL" : null }); }
async function downloadArchive(symbol: R31Symbol, transport: R32Transport | null, fetchImpl: R32Fetch, curlRunner: R32CurlRunner, clock: R32Clock): Promise<{ evidence: R32ArchiveEvidence; rows: readonly R32ArchiveRow[] }> { const urls = archiveUrls(symbol); const selected = transport ?? "NODE_FETCH"; const zip = await requestTransport(symbol, urls.path, urls.url, selected, fetchImpl, curlRunner, clock); const checksum = await requestTransport(symbol, `${urls.path}.CHECKSUM`, urls.checksumUrl, selected, fetchImpl, curlRunner, clock); let parsed: ReturnType<typeof parseR32ArchiveRows> | null = null; let parseError: string | null = null; if (zip.evidence.ok && zip.body) { try { parsed = parseR32ArchiveRows(zip.body, symbol); } catch (error) { parseError = error instanceof Error ? error.message : String(error); } } const publishedChecksum = checksumFromBody(checksum.body); const localSha256 = zip.evidence.rawPayloadSha256; const checksumValid = publishedChecksum !== null && localSha256 !== null && publishedChecksum === localSha256; const emptyCounts: Record<R32ParserMode, number> = { EPOCH_MS: 0, EPOCH_SECONDS: 0, UTC_DATETIME_STRING: 0, ISO_WITH_ZONE: 0 }; const headerSchemaValid = parsed?.headerSchemaValid ?? false; const timestampParserValid = parsed?.timestampParserValid ?? false; const duplicateValid = parsed?.duplicateValid ?? false; const rows = parsed?.rows ?? []; const errorClass: R32ErrorClass | null = parseError ? "ARCHIVE" : !checksumValid && zip.evidence.ok && checksum.evidence.ok ? "CHECKSUM" : zip.evidence.errorClass ?? checksum.evidence.errorClass ?? null; return Object.freeze({ rows, evidence: Object.freeze({ symbol, url: urls.url, checksumUrl: urls.checksumUrl, transportAvailable: zip.evidence.ok && checksum.evidence.ok, zipHttpStatus: zip.evidence.httpStatus, checksumHttpStatus: checksum.evidence.httpStatus, publishedChecksum, localSha256, checksumValid, headerSchemaValid, schemaValid: headerSchemaValid, timestampParserValid, createTimeFormatCounts: Object.freeze(parsed?.createTimeFormatCounts ?? emptyCounts), duplicateValid, rowCount: rows.length, firstTimestamp: rows[0]?.timestamp ?? null, lastTimestamp: rows.at(-1)?.timestamp ?? null, exactDuplicateCount: parsed?.exactDuplicateCount ?? 0, conflictingDuplicateCount: parsed?.conflictingDuplicateCount ?? 0, zipRequest: zip.evidence, checksumRequest: checksum.evidence, errorClass, errorMessage: parseError ?? (!checksumValid && zip.evidence.ok && checksum.evidence.ok ? "Published checksum did not match downloaded ZIP." : null) }) }); }
function classify(archiveReady: boolean, selected: R32Transport | null, liveSuccess: number, admitted: number): Readonly<{ sourceClassification: string; sourceNextStage: string; current: boolean }> { if (!archiveReady) return Object.freeze({ sourceClassification: "SOURCE_REPROBE_INCONCLUSIVE_DUE_TO_ARCHIVE_PARSER_OR_SCHEMA", sourceNextStage: "ARCHIVE_FORMAT_COMPATIBILITY_AUDIT_REQUIRED", current: false }); if (!selected) return Object.freeze({ sourceClassification: "LIVE_TRANSPORT_UNAVAILABLE_IN_CURRENT_EXECUTION_ENVIRONMENT", sourceNextStage: "RUN_REPROBE_FROM_BINANCE_REACHABLE_ENVIRONMENT_REQUIRED", current: false }); if (liveSuccess < 25) return Object.freeze({ sourceClassification: "SOURCE_REPROBE_INCONCLUSIVE_DUE_TO_LIVE_REACHABILITY", sourceNextStage: "LIVE_TRANSPORT_STABILITY_REQUIRED", current: false }); if (admitted === R31_FIELD_MAPPINGS.length) return Object.freeze({ sourceClassification: "BINANCE_METRICS_CURRENT_REGIME_MAPPING_ESTABLISHED", sourceNextStage: "HISTORICAL_METRICS_REGIME_AND_COVERAGE_AUDIT_REQUIRED", current: true }); if (admitted > 0) return Object.freeze({ sourceClassification: "BINANCE_METRICS_PARTIAL_CURRENT_REGIME_MAPPING_ESTABLISHED", sourceNextStage: "HISTORICAL_AUDIT_FOR_ADMITTED_METRICS_FIELDS_REQUIRED", current: false }); return Object.freeze({ sourceClassification: "BINANCE_METRICS_CURRENT_REGIME_MAPPING_INCOMPATIBLE", sourceNextStage: "ALTERNATIVE_OR_PAID_INFORMATION_SOURCE_REQUIRED", current: false }); }
function proxySafeEnv(): Partial<NodeJS.ProcessEnv> { return { HTTP_PROXY: process.env.HTTP_PROXY, HTTPS_PROXY: process.env.HTTPS_PROXY, ALL_PROXY: process.env.ALL_PROXY, NO_PROXY: process.env.NO_PROXY }; }
export type R32RunOptions = Readonly<{ root?: string; protocolCommitSha: string; runId?: string; fetchImpl?: R32Fetch; curlRunner?: R32CurlRunner; dnsLookup?: R32DnsLookup; clock?: R32Clock; env?: Partial<NodeJS.ProcessEnv> }>;

export async function runR32Reprobe(options: R32RunOptions): Promise<R32Result> {
  const root = path.resolve(options.root ?? process.cwd()); const researchDir = path.join(root, "docs", "research"); const receiptPath = path.join(researchDir, "round-032-execution-receipt.json"); const resultPath = path.join(researchDir, "round-032-binance-metrics-environment-result.json"); const markdownPath = path.join(researchDir, "round-032-binance-metrics-environment-result.md"); if (existsSync(receiptPath) || existsSync(resultPath)) throw new Error("R32 execution receipt or result already exists; refusing a second invocation."); mkdirSync(researchDir, { recursive: true }); const clock = options.clock ?? (() => new Date()); const runId = options.runId ?? randomRunId(); const startedAt = iso(clock); const startedReceipt = Object.freeze({ schemaVersion: "m3-r32-execution-receipt-001", runId, protocolCommitSha: options.protocolCommitSha, startedAt, executionType: "BINANCE_METRICS_EXECUTION_ENVIRONMENT_REPROBE", status: "STARTED" as const, r32ExecutionCount: 1 as const }); writeFileSync(receiptPath, `${JSON.stringify(startedReceipt, null, 2)}\n`, { flag: "wx" });
  const fetchImpl = options.fetchImpl ?? fetch; const curlRunner = options.curlRunner ?? defaultCurlRunner; const dnsLookup = options.dnsLookup ?? (async (hostname: string) => (await defaultDnsLookup(hostname, { all: true })).map((entry) => entry.address)); const preflight = await runPreflight(fetchImpl, curlRunner, dnsLookup, clock, options.env ?? proxySafeEnv()); const archiveData = new Map<R31Symbol, { evidence: R32ArchiveEvidence; rows: readonly R32ArchiveRow[] }>(); for (const symbol of R31_SYMBOLS) archiveData.set(symbol, await downloadArchive(symbol, preflight.selectedTransport, fetchImpl, curlRunner, clock)); const archiveEvidence = R31_SYMBOLS.map((symbol) => archiveData.get(symbol)!.evidence); const archiveOverlapReady = archiveEvidence.every((item) => item.transportAvailable && item.checksumValid && item.headerSchemaValid && item.timestampParserValid && item.duplicateValid);
  const requestEvidence: R32RequestEvidence[] = []; const liveData = new Map<string, readonly R31LiveRow[]>(); let formalMappingExecutionCount: 0 | 1 = 0; if (archiveOverlapReady && preflight.selectedTransport !== null) { formalMappingExecutionCount = 1; for (const symbol of R31_SYMBOLS) for (const endpoint of R31_ENDPOINTS) { const request = await requestTransport(symbol, endpoint, liveUrl(symbol, endpoint), preflight.selectedTransport, fetchImpl, curlRunner, clock); let evidence = request.evidence; let rows: readonly R31LiveRow[] = []; if (request.body && evidence.ok) { try { const payload: unknown = JSON.parse(Buffer.from(request.body).toString("utf8")); const parsed = filterR31LiveRows(payload, symbol, endpoint); rows = parsed.rows; evidence = Object.freeze({ ...evidence, rawLiveRowCount: parsed.rawLiveRowCount, outOfWindowRowCount: parsed.outOfWindowRowCount, filteredRowCount: parsed.filteredRowCount, exactDuplicateCount: parsed.exactDuplicateCount, conflictingDuplicateCount: parsed.conflictingDuplicateCount, errorClass: parsed.conflictingDuplicateCount > 0 ? "DUPLICATE" as const : null, errorMessage: parsed.conflictingDuplicateCount > 0 ? "Conflicting duplicate live timestamps." : null }); } catch (error) { const info = errorInfo(error); const errorClass = info.message.includes("not an array") ? "NON_ARRAY" : info.message.includes("Unexpected") ? "NON_JSON" : "SCHEMA"; evidence = Object.freeze({ ...evidence, ok: false, errorClass, errorCode: info.code, errorMessage: info.message, nestedCauseCode: info.nestedCauseCode, stderrPreview: bodyPreview(request.body) }); } } requestEvidence.push(evidence); liveData.set(`${symbol}:${endpoint}`, rows); } }
  const mappingEvidence: Array<ReturnType<typeof evaluateR31Mapping>> = []; const fieldSummaries: R32FieldSummary[] = []; if (formalMappingExecutionCount === 1) for (const mapping of R31_FIELD_MAPPINGS) { const perSymbol = R31_SYMBOLS.map((symbol) => { const archive = archiveData.get(symbol)!; const request = requestEvidence.find((item) => item.symbol === symbol && item.endpointOrArchivePath === mapping.liveEndpoint); if (!archive.evidence.headerSchemaValid || !archive.evidence.checksumValid || !archive.evidence.timestampParserValid || !archive.evidence.duplicateValid) return null; if (!request?.ok || (request.conflictingDuplicateCount ?? 0) > 0) return null; return evaluateR31Mapping(archive.rows, liveData.get(`${symbol}:${mapping.liveEndpoint}`) ?? [], mapping.archiveField, mapping.id, symbol, mapping.liveEndpoint, mapping.liveField); }); const valid = perSymbol.filter((item): item is NonNullable<typeof item> => item !== null); mappingEvidence.push(...valid); const summary = valid.length === R31_SYMBOLS.length ? summarizeR31Field(mapping, valid) : { fieldId: mapping.id, archiveField: mapping.archiveField, liveEndpoint: mapping.liveEndpoint, liveField: mapping.liveField, admitted: false, dominantMapping: null, minimumTimestampCoverage: valid.length === 0 ? 0 : Math.min(...valid.map((item) => item.timestampCoverageRate)), minimumNumericAgreement: valid.length === 0 ? 0 : Math.min(...valid.map((item) => item.numericAgreementRate)) }; fieldSummaries.push(Object.freeze(summary)); }
  const liveSuccessfulRequests = requestEvidence.filter((item) => item.ok && item.errorClass === null).length; const admittedFields = fieldSummaries.filter((item) => item.admitted).map((item) => item.fieldId); const rejectedFields = fieldSummaries.filter((item) => !item.admitted).map((item) => item.fieldId); const resultClass = classify(archiveOverlapReady, preflight.selectedTransport, liveSuccessfulRequests, admittedFields.length); const result: R32Result = Object.freeze({ schemaVersion: "m3-r32-binance-metrics-execution-environment-result-001", researchRoundId: R32_RESEARCH_ROUND_ID, classification: R32_CLASSIFICATION, protocolCommitSha: options.protocolCommitSha, runId, r32ExecutionCount: 1, fixedWindow: Object.freeze({ date: R32_DATE, startTime: R32_START_TIME, endTime: R32_END_TIME, timezone: "UTC" }), inheritedR31Conclusion: Object.freeze({ sourceClassification: "SOURCE_REPROBE_INCONCLUSIVE_DUE_TO_LIVE_REACHABILITY", r31ReprobeExecutionCount: 1 }), archiveEvidence: Object.freeze(archiveEvidence), archiveFilesAvailable: archiveEvidence.filter((item) => item.transportAvailable).length, checksumValidFiles: archiveEvidence.filter((item) => item.checksumValid).length, schemaValidFiles: archiveEvidence.filter((item) => item.headerSchemaValid).length, timestampParserValidFiles: archiveEvidence.filter((item) => item.timestampParserValid).length, archiveOverlapReady, executionEnvironment: preflight, formalMappingExecutionCount, liveLogicalRequests: 25, liveSuccessfulRequests, liveFailedRequests: 25 - liveSuccessfulRequests, requestEvidence: Object.freeze(requestEvidence), fieldSummaries: Object.freeze(fieldSummaries), admittedFields: Object.freeze(admittedFields), rejectedFields: Object.freeze(rejectedFields), admittedFieldCount: admittedFields.length, currentRegimeMappingEstablished: resultClass.current, historicalRegimeMappingEstablished: false, fullHistoricalCoverageCertified: false, sourceClassification: resultClass.sourceClassification, sourceNextStage: resultClass.sourceNextStage, economicOutcomeFilesRead: false, economicEvaluationPerformed: false, tradingEconomicMetricsCalculated: false, modelFitCount: 0, candidateCount: 0, championCount: 0, selectedAlertCount: 0, governance: R32_GOVERNANCE }); writeFileSync(resultPath, `${JSON.stringify(result, null, 2)}\n`, { flag: "wx" }); const completedAt = iso(clock); writeFileSync(receiptPath, `${JSON.stringify(Object.freeze({ ...startedReceipt, status: "COMPLETED", completedAt, resultSha256: r32ResultSha256(result) }), null, 2)}\n`); writeFileSync(markdownPath, renderR32Markdown(result)); return result;
}
export function renderR32Markdown(result: R32Result): string { const archive = result.archiveEvidence.map((item) => `- ${item.symbol}: transport=${item.transportAvailable}, checksum=${item.checksumValid}, schema=${item.headerSchemaValid}, timestampParser=${item.timestampParserValid}, duplicates=${item.duplicateValid}, formats=${JSON.stringify(item.createTimeFormatCounts)}`).join("\n"); const fields = result.fieldSummaries.length === 0 ? "- No formal mapping was executed." : result.fieldSummaries.map((item) => `- ${item.fieldId}: mapping=${item.dominantMapping ?? "null"}, timestampCoverage=${item.minimumTimestampCoverage}, numericAgreement=${item.minimumNumericAgreement}, admitted=${item.admitted}`).join("\n"); return `# Round-032 Binance metrics execution-environment reprobe\n\n- Classification: \`${result.sourceClassification}\`\n- Next stage: \`${result.sourceNextStage}\`\n- Run ID: \`${result.runId}\`\n- r32ExecutionCount: \`${result.r32ExecutionCount}\`\n- Archive overlap ready: \`${result.archiveOverlapReady}\`\n- Formal mapping execution count: \`${result.formalMappingExecutionCount}\`\n- Selected transport: \`${result.executionEnvironment.selectedTransport ?? "null"}\`\n\n## Archive\n\n${archive}\n\n## Mapping\n\n${fields}\n\n## Governance\n\n- economicOutcomeFilesRead: \`${result.economicOutcomeFilesRead}\`\n- economicEvaluationPerformed: \`${result.economicEvaluationPerformed}\`\n- forwardEconomicValuesRead: \`${result.governance.forwardEconomicValuesRead}\`\n- performanceExecutionCount: \`${result.governance.performanceExecutionCount}\`\n- automaticTrading: \`${result.governance.automaticTrading}\`\n- humanDecisionRequired: \`${result.governance.humanDecisionRequired}\`\n- Production unchanged: \`${result.governance.productionUnchanged}\`\n`; }
export function assertR32ProtocolRuntime(): true { if (R32_BASE_SHA !== "96f14392b02ea492a1b2c6f20b47334a3bf3234a") throw new Error("R32 base identity changed."); if (R31_SYMBOLS.length !== 5 || R31_ENDPOINTS.length !== 5 || R31_FIELD_MAPPINGS.length !== 5 || R31_TIMESTAMP_MAPPINGS.length !== 3) throw new Error("R32 inherited mapping cardinality changed."); if (R32_GOVERNANCE.automaticTrading || R32_GOVERNANCE.performanceExecutionCount !== 0 || R32_GOVERNANCE.economicOutcomeFilesRead) throw new Error("R32 governance boundary changed."); return true; }
export function readR32Result(root: string): R32Result { return JSON.parse(readFileSync(path.join(path.resolve(root), "docs", "research", "round-032-binance-metrics-environment-result.json"), "utf8")) as R32Result; }
