export const R22_R8_NOTIFICATION_CAUSAL_INTEGRATION_CONTRACT = Object.freeze({
  phase: "R8_NOTIFICATION_CAUSAL_INTEGRATION_IMPLEMENTATION_ONLY",
  scope: Object.freeze([
    "notificationObservedAt",
    "notification causal integration",
  ]),
  causalInvariant: "informationAsOf <= signalTime <= observedAt <= capturedAt is not assumed; the authoritative notification checks are signalTime <= observedAt and signalTime <= capturedAt.",
  notificationCausalInvariant: "signalTime <= notificationObservedAt",
  observedAtAuthority: "SERVER_WALL_CLOCK at the notification event boundary",
  o05CoveredTypes: Object.freeze([
    "CLAIMED",
    "RETRY_CLAIMED",
    "SKIPPED_DUPLICATE",
    "SKIPPED_EXPIRED",
    "DELIVERY_ATTEMPTED",
    "DELIVERED",
    "DELIVERY_FAILED",
    "DELIVERY_REGISTRY_PERSISTENCE_FAILED",
  ]),
  identity: "notificationDecisionId + event type + terminalEventId where applicable",
  idempotency: "notificationObservationId and payload-derived idempotency are independent of observedAt, capturedAt, and random values",
  sourceRef: "tp_signal_advisories:<signalId>",
  persistence: "Existing R1 ObservationEvidenceCandidate and append-only SupabaseObservationEvidenceStore; no second table or writer",
  sidecar: "Best-effort append that cannot block sendSignalEmail, markSignalSent, markSignalFailed, retry, or scan completion",
  economicFields: "No PnL, forward return, future price, performance, or economic result fields",
  crossSourceIdentity: ["signalId", "symbol", "direction", "signalTime", "strategyId", "strategyVersion"],
  eventTypes: Object.freeze([
    "CLAIM_DECISION",
    "DELIVERY_ATTEMPTED",
    "DELIVERED",
    "DELIVERY_FAILED",
    "DELIVERY_REGISTRY_PERSISTENCE_FAILED",
  ]),
  outOfScope: Object.freeze([
    "review timestamps",
    "R9 readiness closure",
    "R10 readiness closure",
    "observation execution",
    "historical backfill",
    "performance",
    "backtest",
    "selection",
    "economic evaluation",
    "new market data",
    "Production",
  ]),
} as const);

export const R22_R8_NOTIFICATION_CAUSAL_INTEGRATION_IMPLEMENTATION_STATUS = Object.freeze({
  r1FoundationImplemented: true,
  r2QualitySnapshotProducerImplemented: true,
  r3MarketContextProducerImplemented: true,
  r4RiskAdvisoryProducerImplemented: true,
  r5HistoricalReviewMetadataProducerImplemented: true,
  r6AlertIntelligenceProducerImplemented: true,
  r6AcceptanceStatus: "ACCEPTED",
  r7PresentationEvidenceBoundaryImplemented: true,
  r7AcceptanceStatus: "ACCEPTED",
  r8NotificationCausalIntegrationImplemented: true,
  introducesCapabilities: Object.freeze(["notificationObservedAt", "notificationCausalIntegration"]),
  closesReadinessNodes: Object.freeze([]),
  s01Status: "SOURCE_READY",
  s02Status: "SOURCE_READY",
  s03Status: "SOURCE_READY",
  s04Status: "SOURCE_READY",
  s04AcceptedReady: true,
  s05Status: "SOURCE_READY",
  s05AcceptedReady: true,
  s06Status: "SOURCE_READY",
  s06AcceptedReady: true,
  s07Status: "FAIL",
  s08Status: "FAIL",
  s09Status: "FAIL",
  s10Status: "FAIL",
  observationInstrumentationImplemented: false,
  observationAuthorized: false,
  observationExecuted: false,
  performanceAuthorized: false,
  performanceExecutionCount: 0,
  performanceLedgerPresent: false,
  economicValuesRead: false,
  forwardReturnRead: false,
  newMarketDataFetched: false,
  historicalBackfillExecuted: false,
  productionUnchanged: true,
  baseline002Status: "NOT_FROZEN",
  m3JStatus: "BLOCKED",
  m4Status: "NOT_STARTED",
  humanDecisionRequired: true,
  automaticTrading: false,
} as const);

export const R22_R8_NOTIFICATION_CAUSAL_INTEGRATION_FINAL_DECISION = Object.freeze({
  decision: "ROUND-022 R8 NOTIFICATION CAUSAL INTEGRATION IMPLEMENTATION READY",
  nextStage: "STOP_PENDING_R8_ACCEPTANCE",
  r8Authorized: true,
  closesReadinessNodes: Object.freeze([]),
  r9Started: false,
  r10Started: false,
} as const);
